name: React CI with SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Install Dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Hotstar-Clone
            -Dsonar.projectName=Hotstar-Clone
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sourceEncoding=UTF-8
      # 7️⃣ Build React App
      - name: Build React app
        run: npm run build

      # 8️⃣ Zip build artifact
      - name: Zip build folder
        run: |
          zip -r react-build-${{ github.run_number }}.zip build

      # 9️⃣ Upload artifact to Nexus
      - name: Upload to Nexus
        run: |
          curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
          --upload-file react-build-${{ github.run_number }}.zip \
          ${{ secrets.NEXUS_URL }}/repository/${{ secrets.NEXUS_REPOSITORY }}/react/react-build-${{ github.run_number }}.zip

            



            

     
